name: 'Publish to itch.io'

on:
  workflow_call:
    inputs:
      postfix:
        required: false
        type: string
        default: ''

jobs:
  publish:
    continue-on-error: true
    name: 'Publish'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Windows (ZIP)"
            channel: 'windows'
            artifact: 'build-win32-zip${{ inputs.postfix }}'
            file: 'inochi-session-win32.zip'

          - name: "macOS (ZIP)"
            channel: 'osx'
            artifact: 'build-osx-zip${{ inputs.postfix }}'
            file: 'inochi-session-osx.zip'

          - name: "macOS (DMG)"
            channel: 'osx-dmg'
            artifact: 'build-osx-dmg${{ inputs.postfix }}'
            file: 'Install_Inochi_Session.dmg'

          - name: "Linux"
            channel: 'linux'
            artifact: 'build-linux-zip${{ inputs.postfix }}'
            file: 'inochi-session-linux.zip'
    steps:
    - name: 'Download ${{ matrix.config.artifact }}...'
      uses: actions/download-artifact@v4
      with:
        name: '${{ matrix.config.artifact }}'


    - name: 'Publishing ${{ matrix.config.name }} to Itch...'
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: ${{ matrix.config.channel }}
        ITCH_GAME: inochi-session
        ITCH_USER: kitsunebi-games
        VERSION_FILE: version.txt
        PACKAGE: 'out/${{ matrix.config.file }}'
