# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build and Release

on:
  push:
    # Push all normally versioned tags
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  # Full Release
  # This needs "gh-publish-demo" due to the fact that
  # we need to overwrite the artifacts related.
  build:
    if: ${{ ! contains(github.ref_name, 'rc') }}
    uses: './.github/workflows/build.yml'
    with:
      target_ref: '${{ github.ref_name }}'
      variant: 'full'
      generate_version: true
      do_package: true

  itch-publish:
    needs: build
    uses: './.github/workflows/publish-itch.yml'
    secrets: inherit

  gh-publish:
    needs: build
    uses: './.github/workflows/publish-gh.yml'
    secrets: inherit
  
  # Delete artifacts after use.
  cleanup:
    if: 'always()'
    runs-on: ubuntu-latest
    needs: [itch-publish, steam-publish, gh-publish]
    steps:
    - uses: GeekyEggo/delete-artifact@v5
      with: 
        name: |
          *